export enum States {
  BOOT_STATE = 'bootState',
  PRELOAD_STATE = 'preloadState'
}

export enum Levels {
  LEVEL_ONE = 0,
  LEVEL_TWO = 1
}

export enum TankLayout {
  GREEN_FORTRESS, GREEN_ARTILERY, GREEN_HUNTER, GREEN_RECON, GREEN_LIGHT,
  GREY_FORTRESS, GREY_ARTILERY, GREY_HUNTER, GREY_RECON, GREY_LIGHT,
  CANDY_FORTRESS, CANDY_ARTILLERY, CANDY_HUNTER, CANDY_RECON, CANDY_LIGHT,
  DARK_FORTRESS, DARK_ARTILLERY, DARK_HUNTER, DARK_RECON, DARK_LIGHT
}

export enum ComponentType {
  MOVABLE = 'movable'
}
